executable              = /afs/cern.ch/user/c/ccarriva/dim6dim8/EFT_studies/run_madgraph_condor.sh
arguments               = PROCESS MODEL BLOCK
output                  = /afs/cern.ch/user/c/ccarriva/dim6dim8/EFT_studies/logs/run_PROCESS_MODEL_cuts.out 
error                   = /afs/cern.ch/user/c/ccarriva/dim6dim8/EFT_studies/logs/run_PROCESS_MODEL_cuts.err 
log                     = /afs/cern.ch/user/c/ccarriva/dim6dim8/EFT_studies/logs/run_PROCESS_MODEL.log 
+JobFlavour             = "nextweek" 
periodic_remove         = JobStatus == 5  
WhenToTransferOutput    = ON_EXIT_OR_EVICT 

Queue 1